[package]
name = "embeddings"
version = "0.1.154"
edition = "2021"
publish = false

[dependencies]
llamacpp-rs = { path = "../../llamacpp-rs", version = "0.1.0" }
hf-hub = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
encoding_rs = { workspace = true }

[features]
cuda = ["llamacpp-rs/cuda"]
metal = ["llamacpp-rs/metal"]
vulkan = ["llamacpp-rs/vulkan"]
mkl = ["llamacpp-rs/mkl"]

[lints]
workspace = true
