//! Raw, unsafe bindings to llama.cpp, generated by `bindgen` in `build.rs`.
//!
//! This module is private to the crate; see the rest of `llamacpp-rs` for
//! the safe, idiomatic wrapper built on top of it.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(unpredictable_function_pointer_comparisons)]
#![allow(missing_docs)]
#![allow(missing_debug_implementations)]
#![allow(dead_code)]
#![allow(unused)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
