[package]
name = "mtmd"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
llama-cpp = { path = "../../llama-cpp", version = "0.1.0", features = ["mtmd"] }
clap = { workspace = true, features = ["derive"] }
encoding_rs = { workspace = true }

[features]
cuda = ["llama-cpp/cuda"]
metal = ["llama-cpp/metal"]
vulkan = ["llama-cpp/vulkan"]
mkl = ["llama-cpp/mkl"]

[lints]
workspace = true

[[example]]
name = "mtmd"
path = "src/mtmd.rs"
