[package]
name = "mtmd"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
llamacpp-rs = { path = "../../llamacpp-rs", version = "0.1.0", features = ["mtmd"] }
clap = { workspace = true, features = ["derive"] }
encoding_rs = { workspace = true }

[features]
cuda = ["llamacpp-rs/cuda"]
metal = ["llamacpp-rs/metal"]
vulkan = ["llamacpp-rs/vulkan"]
mkl = ["llamacpp-rs/mkl"]

[lints]
workspace = true

[[example]]
name = "mtmd"
path = "src/mtmd.rs"
