[package]
name = "simple"
version = "0.1.154"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llamacpp-rs = { path = "../../llama-cpp", version = "0.1.0" }
hf-hub = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
encoding_rs = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
cuda = ["llamacpp-rs/cuda"]
metal = ["llamacpp-rs/metal"]
vulkan = ["llamacpp-rs/vulkan"]
mkl = ["llamacpp-rs/mkl"]

[lints]
workspace = true
